version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: php_crud
      DB_USER: php_crud_user
      DB_PASS: secret

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: php_crud
      MYSQL_USER: php_crud_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data:
